[build]
  # Copy Flask template index to root for static hosting
  command = "cp templates/index.html ./index.html"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.9"

[dev]
  framework = "flask"
