[build]
  publish = "templates"
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200
  force = true

[functions]
  directory = "functions"

[dev]
  framework = "flask"
